#!/usr/bin/env bash
#uses ssh to connect to your server using the private key ~/.ssh/holberton with the user ubuntu

num=$#

if [ $num -lt 4 ]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
	exit 1
fi

echo "scp -o StrictHostKeyChecking=no -i $4 $1 $3@$2:~/"
