#!/usr/bin/env bash
# A script to install haproxy server

apt-get update
# apt-get install software-properties-common -y
# add-apt-repository ppa:vbernat/haproxy-1.7 -y
# apt-get update
# apt-get install haproxy=1.7.\* -y
apt-get install haproxy -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web1 34.148.10.186:80 check
        server web2 35.175.187.175:80 check
" | tee -a /etc/haproxy/haproxy.cfg
service haproxy start
