#!/usr/bin/env bash
# configure nginx server

apt update
apt-get -y install nginx
ufw allow 'Nginx HTTP' 2> /dev/null
# sed -i '/listen 80 default_server;/ a \\tlisten 0.0.0.0:80 default_server;' /etc/nginx/sites-available/default
service nginx restart
