#!/usr/bin/env bash
# more Superstition
num=1

while [ $num -ne 21 ]
do
	echo "$num"
	case $num in
		4)
			echo 'bad luck from China'
			;;

		9)
			echo 'bad luck from Japan'
			;;

		17)
			echo 'back luck from Italy'
			;;
	esac		
	((num++))
done
