#!/usr/bin/env bash
# script for changing IP in a docker isnstance

cp /etc/hosts ~/hosts.new
sed -i '/localhost/s/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '/facebook.com/s/157.240.11.35/8.8.8.8/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
